name: CI with Gradle

on:
  workflow_dispatch:
    inputs:
      uiAutomator2Version:
        description: 'uiAutomator2Version'
        required: true
        default: '2.25.2'
      cucumberTags:
        description: 'cucumberTags'
        required: true
        default: demo
      emulatorProfile:
        type: choice
        description: 'emulatorProfile'
        options:
          - android-33-ext5;google_apis_playstore;x86_64
          - android-34;google_apis_playstore;x86_64

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get install pulseaudio
        npm install -g appium
        appium driver install uiautomator2@$UI_AUTOMATOR2_VERSION
      shell: bash
      env:
        UI_AUTOMATOR2_VERSION: ${{ github.event.inputs.uiAutomator2Version }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Clone mobile app repo
      uses: actions/checkout@main
      with:
        repository: truong-dang-gft/sunflower
        token: ${{ secrets.TRUONG_GITHUB_TOKEN }}

    - name: Build mobile app
      run: ./gradlew assembleDebug -x test

    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Create and boot emulator
      run: |
        function waitForEmulatorToStart() {
          boot_completed=false
          fail_counter=0
          while [[ "$boot_completed" == false ]]; do
            status=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Booting emulator ... Elapsed time: $fail_counter s"
            
            if [[ "$status" == "1" ]]; then
              boot_completed=true
            else
              (( fail_counter += 10))
              sleep 10
            fi
          done
        }
        
        echo $PATH
        echo $ANDROID_HOME
        export ANDROID_SDK_HOME=$ANDROID_HOME
        echo $ANDROID_SDK_HOME
        
        echo no | sdkmanager --install "system-images;$EMULATOR_PROFILE"
        echo no | avdmanager create avd -n emulator-5554 -k "system-images;$EMULATOR_PROFILE"
        
        adb start-server
        
        $ANDROID_HOME/emulator/emulator -avd emulator-5554 -no-window -no-boot-anim -no-audio -no-snapshot &
        
        adb wait-for-device
        adb devices
        
        waitForEmulatorToStart
      shell: bash
      env:
        EMULATOR_PROFILE: ${{ github.event.inputs.emulatorProfile }}

    - name: Install mobile app
      run: |
        
        function installApk() {
          is_installed=false
          fail_counter=0
          maximum_failed_time=10
          while [[ "$is_installed" == false ]] && [[ $fail_counter -lt $maximum_failed_time ]]; do
            status=$(adb -P 5037 -s emulator-5554 install -g ./app/build/outputs/apk/debug/app-debug.apk | tr -d '\r')
          
            if [[ "$status" == *"Success"* ]]; then
              is_installed=true
            else
              (( fail_counter += 1))
              sleep 20
            fi
          done
        }
        
        installApk
      shell: bash

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clone appium kotlin repo
      uses: actions/checkout@master
      with:
        repository: truong-dang-gft/demo-appium-kotlin
        token: ${{ secrets.TRUONG_GITHUB_TOKEN }}

    - name: Build and run cucumber tests
      run: |
        ./gradlew cucumber --tags @$CUCUMBER_TAGS
      shell: bash
      env:
        CUCUMBER_TAGS: ${{ github.event.inputs.cucumberTags }}
        
